### ISSUE TITLE
On requirements

### ISSUE THREAD

**Issue by dodyg** [silverkeytech/travel-planner#1]
The requirements needs adjustments

One of the most pressing needs is travel cost estimator.

Scenario:

- I travel with 3 people for three days
- I want to hire a private minibus ($$$$)
- I need accommodation for 4 people. 
  -- 1 double room
  -- 2 single room
- I want safari for full day

What would be the instant cost estimator for this? It's not the final price but it will allow people to approximate their trip quickly.

**Comment by dodyg** [comment]
Who will use the system?

- Egyptians
- Foreigners that live in Egypt
- Foreign tourists

They all have different needs.  You need to write the profile for each. Egyptians mostly won't need a pickup from the airport for example. Also the price and fees for Egyptians are different compared to foreigners.

**Comment by dodyg** [comment]
# No login required

Do not impose login requirement for customers. They don't need it.

**Comment by Rofaydaaa** [comment]
### Requirements are updated.
[Kindly check our wiki](https://github.com/silverkeytech/travel-planner/wiki/Requirements)
We are open for any feedback.
